### ISSUE TITLE
Migration to node20

### ISSUE THREAD

**Issue by pavel-faltynek** [EndBug/latest-tag#60]
Hey,

would it be possible to migrate to `node 20`?
Starting to get warnings about `node 16` deprecation when using this action.
Hopefully it might be only simple change in `action.yml` (having no clue about `.js` stuff 😁)?

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Thank you.

**Comment by EndBug** [comment]
@all-contributors please add @pavel-faltynek for their maintenance contribution
