### ISSUE TITLE
nightly release updating latest tag

### ISSUE THREAD

**Issue by ziyangczi** [EndBug/latest-tag#8]
Hi there, I am trying to use the latest tag to help me update the tag on a scheduled nightly build, however the current flow is blocking me from doing that because it only proceed during a 'publish' action, may I ask to add some config option to skip this check for my use case?

see https://github.com/napari/napari/runs/1534202094?check_suite_focus=true

**Comment by EndBug** [comment]
Hi, that seems like a good idea
I have a lot of stuff to do in this period, and I may take a lot of time to solve this issue. Feel free to open a PR if you need it right away!
Otherwise, I'll notify you here once I add this 👍🏻

**Comment by EndBug** [comment]
@all-contributors please add @ziyangczi for their idea

**Comment by EndBug** [comment]
Hi, this has been fixed by the new minor version, `v1.4.0` (also via `v1` and `latest`).

Thanks for the issue, feel free to let me know if you find any other issue :)
